# Generated by Django 5.0.1 on 2024-01-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0003_homepage_body")]

    operations = [
        migrations.RemoveField(model_name="homepage", name="body"),
        migrations.AddField(
            model_name="homepage",
            name="banner_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
