# Generated by Django 5.0.1 on 2024-02-07 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_rename_homepagecarrouselimages_homepagecarouselimages"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HomePageCarouselImages", new_name="HomePageCarrouselImages"
        )
    ]
