# Generated by Django 5.0.1 on 2024-02-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0010_homepagecarouselimages_and_more")]

    operations = [
        migrations.AlterField(
            model_name="homepagecarouselimages",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        )
    ]
