# Generated by Django 5.0.1 on 2024-01-26 16:15

import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("flex", "0002_flexpage_content")]

    operations = [
        migrations.AlterField(
            model_name="flexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_and_text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add your title", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Add additional text", required=True
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("full_richtext", streams.blocks.RichTextBlock()),
                    ("simple_richtext", streams.blocks.SimpleRichTextBlock()),
                    (
                        "cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        max_length=60, required=True
                                    ),
                                ),
                                (
                                    "cards",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        help_text="Imagen de 500x500px",
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=40, required=True
                                                    ),
                                                ),
                                                (
                                                    "text",
                                                    wagtail.blocks.TextBlock(
                                                        max_length=200, required=True
                                                    ),
                                                ),
                                                (
                                                    "button_page",
                                                    wagtail.blocks.PageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "button_url",
                                                    wagtail.blocks.URLBlock(
                                                        help_text="Si el boton de arriba esta seleccionado, este no se tomara en cuenta",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "button_text",
                                                    wagtail.blocks.CharBlock(
                                                        default="Learn More",
                                                        max_length=40,
                                                        required=True,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "cta",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        max_length=60, required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic"], required=True
                                    ),
                                ),
                                (
                                    "button_page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                ("button_url", wagtail.blocks.URLBlock(required=False)),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(
                                        default="Learn More",
                                        max_length=40,
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        )
    ]
