# Generated by Django 5.0.1 on 2024-02-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("subscribers", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="subscribers",
            options={
                "verbose_name": "Subscriber",
                "verbose_name_plural": "Subscribers",
            },
        )
    ]
